name: 'Salesforce Code Analyzer Annotation'
description: 'An action that creates an annotation for the output of the Salesforce Code Analyzer'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  repo-token:
    type: string
    description: Github personal access token
    required: true
    default: ${{ github.token }}