name: 'Salesforce Code Analyzer Annotation'
description: 'An action that creates an annotation for the output of the Salesforce Code Analyzer'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  fail-on-error:
    type: boolean
    description: Indicate whether to have a failure annotation when there are errors
    required: true
    default: true
  path:
    type: string
    description: path the results json file
    required: false
  repo-token:
    type: string
    description: Github personal access token
    required: true
    default: ${{ github.token }}